# Базовый образ для запуска приложения
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Базовый образ для сборки приложения
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Crud.Api.csproj", "./"]
RUN dotnet restore "./Crud.Api.csproj"
COPY . .
WORKDIR "/ProductsCrudApi/."
RUN dotnet build "Crud.Api.csproj" -c Release -o /app/build

# Публикация приложения
FROM build AS publish
RUN dotnet publish "Crud.Api.csproj" -c Release -o /app/publish

# Финальный образ
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Crud.Api.dll"]
